service: sheet-bot

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  sheetbot:
    handler: bot-handler.webHook
    events:
      - http:
          method: any
          path: web-hook
plugins:
  - serverless-ngrok-tunnel
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  ngrokTunnel:
    tunnels:
      - port: 3000

frameworkVersion: '2'